version: '3.7'
services:
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'

  server:
    build: .
    image: jasoncalalang/mean-backend
    ports:
      - '3000:3000'
    links:
      - mongo-db
    env_file:
      - .env

  client:
    build: client
    image: jasoncalalang/mean-frontend
    ports:
      - '80:80'
    env_file:
      - client/.env